#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/DefinitelyATestOrg/sam-go/v2,github.com/stainless-sdks/sam-go/v2"

go build -o terraform-provider-sam
